### ISSUE TITLE
Crashes When I press a number on the keyboard

### ISSUE THREAD

**Issue by Expertsonicgamer32x** [hamhub7/nx-TAS#8]

**Comment by hamhub7** [comment]
I'll need more details than that. What fw version are you on and what atmosphere version are you on? It is optimized for the latest

**Comment by TopoIogist** [comment]
did you recompile nx-tas? I had similar problems when using an outdated binary

**Comment by Expertsonicgamer32x** [comment]
i did not compile anything and everything is up to the latest versions i checked EVERYHTING

**Comment by Expertsonicgamer32x** [comment]
and have fun being mad
